App\Entity\Location:
  properties:
    city:
      - NotBlank:
          groups: ['create', 'edit']

    latitude:
      - Range:
          min: -90
          max: 90
          notInRangeMessage: You must choice between -90 and 90
          groups: ['create', 'edit']

    longtitude:
      - Range:
          min: -180
          max: 180
          notInRangeMessage: You must choice between -180 and 180
          groups: ['create', 'edit']

App\Entity\Measurement:
  properties:
    celsius:
      - Range:
          min: -50
          max: 50
          notInRangeMessage: You must choice between -50 and 50
          groups: ['create', 'edit']